from django.contrib import admin
from django.urls import path
from achievements_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autorization/', views.autorization, name = 'autorization'),
    path('recovery/', views.recovery, name = 'recovery'),
    path('registration/', views.registration, name = 'registration'),
    path('check_user/', views.check_user, name = 'check_user'),
    path('information/', views.information, name = 'information'),
    path('passwordReset/', views.passwordReset, name = 'passwordReset'),
    path('registerUser/', views.registerUser, name = 'registerUser'),
    path('check_login/', views.check_login, name = 'check_login'),
    path('check_phone/', views.check_phone, name = 'check_phone'),
    path('check_email/', views.check_email, name = 'check_email'),
    path('editUserInformation/', views.editUserInformation, name = 'editUserInformation'),
    path('', views.mainPage, name = 'mainPage'),
    path('userInformation/', views.userInformation, name = 'userInformation'),
    path('panel/', views.panel, name = 'panel'),
    path('editPassword/', views.editPassword, name = 'editPassword'),
    path('scoreUser/', views.scoreUser, name = 'scoreUser'),
    path('check_password/', views.check_password, name = 'check_password'),
    path('mainPageProfile/', views.mainPageProfile, name = 'mainPageProfile'),
    path('loginUser/', views.loginUser, name = 'loginUser'),
    path('noProfile/', views.noProfile, name = 'noProfile'),
    path('myAchievement/', views.myAchievement, name = 'myAchievement'),
    path('securityProfile/', views.securityProfile, name = 'securityProfile'),
    path('editEmail/', views.editEmail, name = 'editEmail'),
    path('editPhone/', views.editPhone, name = 'editPhone'),
    path('emailReset/', views.emailReset, name = 'emailReset'),
    path('phoneReset/', views.phoneReset, name = 'phoneReset'),
    path('confirmation/', views.confirmation, name = 'confirmation'),
    path('statusReset/', views.statusReset, name = 'statusReset'),
    path('check_status/', views.check_status, name = 'check_status'),
    path('check_isActiveNotification/', views.check_isActiveNotification, name = 'check_isActiveNotification'),
    path('notification/', views.notification, name = 'notification'),
    path('editActiveNotification/', views.editActiveNotification, name = 'editActiveNotification'),
    path('countNotification/', views.countNotification, name = 'countNotification'),
    path('returnNotification/', views.returnNotification, name = 'returnNotification'),
    path('editStatusNotification/', views.editStatusNotification, name = 'editStatusNotification'),
    path('returnAchievement/', views.returnAchievement, name = 'returnAchievement'),
    path('newLike/', views.newLike, name = 'newLike'),
    path('deleteLike/', views.deleteLike, name = 'deleteLike'),
path('check_Like/', views.check_Like, name = 'check_Like'),
path('photoUser/', views.photoUser, name = 'photoUser'),
]